language: scala

scala:
  - 2.12.6

python:
  - 2.7

sudo: false

jdk:
  - oraclejdk8
  
services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.protobuf-2.6.1/src

install:
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xzvf protobuf-2.6.1.tar.gz
  - pushd protobuf-2.6.1 && ./configure --prefix=/usr && make && sudo make install && popd
  - rvm use 2.2.8 --install --fuzzy
  - gem install sass jekyll:3.2.1

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates (https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

jobs:
  include:
    - stage: "Validate and verify modules"
      name: "Validate and verify API"
      script: sbt ++$TRAVIS_SCALA_VERSION ";validate-api; validate-core"
    - name: "Run API functional tests"
      script: ./bin/func-test-api-travis.sh
    - name: "Validate portal"
      script: sbt ++$TRAVIS_SCALA_VERSION "validate-portal"
    - name: "Run portal functional tests"
      script: ./bin/func-test-portal.sh
    - name: "Verify and run coverage on API and portal"
      script: sbt ++$TRAVIS_SCALA_VERSION "verify" && bash <(curl -s https://codecov.io/bash)
    - stage: "Post-validate/verify tasks"
      name: "Publish documentation changes (gh-pages)"
      script: sbt ";project docs; publishMicrosite"
